version: "3"
services:
  app:
    build: ./
    container_name: 'launch-dev'
    working_dir: /home/node/app
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./src:/home/node/app/src
      - ./config:/home/node/app/config
      - ./gatsby-browser.js:/home/node/app/gatsby-browser.js
      - ./gatsby-config.js:/home/node/app/gatsby-config.js
      - ./package.json:/home/node/app/package.json
      - ./.env:/home/node/app/.env
    command: >
      npm run develop
