version: "3"
services:
  app:
    build: ./
    container_name: 'launch-dev'
    working_dir: /home/node/app
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - cache:/home/node/app/.cache
    command: >
      npm run develop

volumes:
  node_modules:
  cache: